server:
  port: 8081

spring:
  application:
    name: scannota-bff
  profiles:
    active: ${ENV:dev}
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=10m

client:
  scannota-api:
    url: ${SCANNOTA_API_CLIENT_URL:}
    token: ${SCANNOTA_API_CLIENT_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30}

security:
  jwt:
    uri: /**
    header: Authorization
    prefix: Bearer
    secret: a-string-secret-at-least-256-bits-long
management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  version: '@project.version@'
  api-docs:
    groups:
      enabled: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false