server:
  port: 8081

spring:
  application:
    name: scannota-bff
  profiles:
    active: ${ENV:dev}
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=10m

client:
  scannota-api:
    url: ${SCANNOTA_API_CLIENT_URL:}

security:
  jwt:
    uri: /**
    header: Authorization
    prefix: Bearer
    secret: secret
management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  version: '@project.version@'
  api-docs:
    groups:
      enabled: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false