server:
  port: 8080

spring:
  application:
    name: desafio-backend-it-arc-api
  profiles:
    active: ${ENV:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=10m

client:
  mock:
    url: ${MOCK_CLIENT_URL:http://mock:8082}

security:
  jwt:
    uri: /**
    header: Authorization
    prefix: Bearer
    secret: secret
management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  version: '@project.version@'
  api-docs:
    groups:
      enabled: false
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false